title: Denobi's Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Hi, my name is Gustavo Denobi. Welcome to my portfolio!
  Here you can find information about many different projects, from robotics and prototyping to deep learning based microphones.
  Please contact me if you have any question.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://gustavodenobi.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Gustavo Denobi # add your name
author-img: denobi.jpg # add your photo
about-author: I am a creator.</br> Mechatronics and software engineer student with focus on data science and robotics. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: gustavodenobi # add your Github handle
social-linkedin: denobi # add your Linkedin handle
social-email: gustavodenobi@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]